import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'



function MyApp({ Component, pageProps }) {
  return (
    <>
  
      <Head>
        <title>Zeep</title>
      

        <link rel="icon" type="image/x-icon" href="/2.png"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/web.png" />
   </Head>

        <Layout >
            <Component {...pageProps} />
        </Layout>
        
    </>
  )
}

export default MyApp
