import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'

function MyApp({ Component, pageProps }) {

  return (
    <>
      <Head>
        <title>---</title>
        <link rel="icon" type="image/x-icon" href="/2.png"></link>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>

      </Head>

        <Layout >
            <Component {...pageProps} />
        </Layout>
        
    </>
  )
}

export default MyApp
