import 'prismjs/themes/prism.css'; // Tema Claro
import 'prismjs/themes/prism-okaidia.css'; // Tema oscuro
import '../styles/globals.css'
import Head from 'next/head'
import Layout from '../components/Layout'


function MyApp({ Component, pageProps }) {
  return (
    <>
  
      <Head>
      <title>Zeep</title>
      <meta charSet="UTF-8"></meta>
       <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/img/web.png" />
   </Head>
 
        <Layout >
            <Component {...pageProps} />
        </Layout>

    </>
  )
}

export default MyApp
